### PR TITLE
login/regis fully functional pages

### PR DESCRIPTION
**Pull request by harsandeep1**
Here are the things achieved via this PR

- To run the code, please use these set of commands: npm install, sequelize db:migrate, nodemon
- Users have login options as well as signup options.
- Users can sign in locally or authenticate with google.
- Unauthorized users are being redirected to the signup page, where they can sign in.
- Authorized users are being directed to the dashboard.
- User info is being stored in the DB. A few tweaks or tune-ups are still needed.

Next set of changes possible with the following PR or future:

- Add middleware routes so that unauthorized users can access the dashboard. 
- Remove Facebook authentication

### CODE REVIEW

**Comment by apainintheneck** [comment]
I'm having problems running the code locally. The sequelize db:migrate commands is not working for me at all. Is there something else I need to install to get this working?

Screen Shot 2021-11-23 at 10 00 39 AM

**Comment by apainintheneck** [comment]
Okay, I just figured out that you have to install the sequelize-cli (please mention details like this in the future). I am however running into an access denied for user error. It looks like some of the old problems with the config.js file are cropping up again. The environment variable names seem to be wrong again in that file and I tried fixing them but that didn't seem to help. Do you remember how you solved this issue last time?

Once, you fix those problems I think it would also be a good idea to add a build script to the package.json file to set up the database to make it easier to run locally and work with Heroku. Somethings like this https://stackoverflow.com/a/67970874

**Comment by apainintheneck** [comment]
Also, if you update the .env file, you'll have to add that to the drive folder so that we can all get access to that.

**Comment by apainintheneck** [comment]
Screen Shot 2021-11-23 at 10 08 07 PM
Now I'm getting this error. Also, the .env variables were changed from the last version which breaks all of the code in dbPool.js so that's also a problem that must be fixed.

**Comment by apainintheneck** [comment]
Screen Shot 2021-11-23 at 10 17 22 PM
What version of Node are you using?

**Comment by harsandeep1** [comment]
most latest node version. Once all the dependencies were installed, all I did is npm install, [ sequelize db:migrate] if db not updated or created, and nodemon in the end.

**Comment by apainintheneck** [comment]
@harsandeep1 The login is working for me now but it fails to redirect users that are not logged in to the landing page. That's the next thing that needs to be worked on.

**Comment by apainintheneck** [comment]
I cleaned up the config.js file and added a more attractive log out button to the sidebar. I'm going to try deploying this branch to Heroku before merging it in. Also, I'll share the updated .env file after I get this working.

**Comment by apainintheneck** [comment]
Okay, this branch is building and deploying correctly which is really good news. There are two things that need to be fixed before this branch can be merged in. Essentially, they have to do with the URI redirects used for Google and Facebook OAuth logins.

The following need to be added as valid redirect URIs:
- Google: http://sqlstudy.herokuapp.com/auth/google/callback
- Facebook: http://sqlstudy.herokuapp.com/auth/facebook/callback

**Comment by apainintheneck** [comment]
I'm going to redeploy the main branch while we wait for these changes.

**Comment by apainintheneck** [comment]
@harsandeep1 Let me know when you're done adding those URIs to Google and Facebooks OAuth so I can try deploying the branch again. Also, I don't have a Facebook account so one of you guys will need to test that for yourself.

**Comment by brycerandolph** [comment]
Just wanted to drop a comment that I was able to test everything and everything was working on my machine. This branch is almost done.

**Comment by apainintheneck** [comment]
The code is completely working except for the OAuth stuff which needs to be updated on the Google and Facebook websites. Merging.

**Pull request merged**
