### PR TITLE
Updated sidebar.ejs and admin-sidebar.ejs styles.

### PR DESCRIPTION
**Pull request by apainintheneck**
Updated sidebar.ejs and admin-sidebar.ejs styles by modifying styles.css and admin.css respectively.

Check the following routes to make sure it looks good.
- /
- /dashboard
- /sandbox
- /admin

### CODE REVIEW

**Comment by apainintheneck** [comment]
Screen Shot 2021-11-19 at 7 25 03 PM
This is what it looks like now.

**Comment by apainintheneck** [comment]
Moved all sidebar styles into sidebar.css and updated the sidebar.ejs and admin-sidebar.ejs files to work with these updates. Then, I updated all pages that use a sidebar with these new files by changing the import and link statements.

I also added the jquery and bootstrap css imports to the imports.ejs file to make that clearer.

The styles.css file now only has styles used by the index.ejs page.

Added 2rem of margin to #content id in the sidebar.ejs file.

When adding sidebar.ejs to your page follow the instructions at the top of the file. The main thing is to include imports.ejs and sidebar.css and also wrap all your content in a tag with the id="content". You'll need to click around to get a feel for this PR because it's a lot of small UI improvements.

**Comment by brycerandolph** [comment]
Looks great and all the links were working. I also appreciate the changes to file organization. Merge when you are ready.

**Comment by apainintheneck** [comment]
For documentation purposes, I'm going to add more information here.

I split the styles in the styles.css file into two files. As a result, I changed the head.ejs file to reflect those changes.

Changes:
- styles.css split into the styles.css file which holds the styles for the landing, login, about and sign up pages and the sidebar.css file which is used by all internal pages like the sandbox and the admin pages. This file was split because there were competing styles.
- As a result, I changed the head.ejs file to remove the styles.css file because it's not needed for the internal pages. You have to add styles.css or sidebar.css file to the head tag manually.

If you are building...
- an external page: Include head.ejs and add styles.css to the head tag.
- an internal page: Include head.ejs and add sidebar.ejs to the head tag while including sidebar.ejs at the top of the body tag and wrapping all site content with a div tag that has the id="content" which handles all of the indentation necessary to coexist with the sidebar.

**Pull request merged**
