### PR TITLE
Working Copy of /quiz2

### PR DESCRIPTION
**Pull request by brycerandolph**
This is a hardcoded example of the chapter 2 quiz. It has my questions/answers and is a template for how we will make the other sections. Do not merge please, @harsandeep1 will be working on this a bit more still.

### CODE REVIEW

**Comment by apainintheneck** [comment]
Two things come to mind.

1. It would probably be a good idea to have a landing page where links to and descriptions of all of the quizzes are shown. This could be at for example /quizzes
2. It might be a good idea to just have one get route for quizzes and pass a parameter that determines the quiz that is going to be displayed. So if none are passed in you just display the quiz landing page otherwise you display the quiz itself. Something like /quizzes?id=1 would pull up the first quiz.
3. Also, make sure to remove unused routes like /quiztester or the duplicate /quiz2 route.

Let me know what you think about that.

**Comment by apainintheneck** [comment]
The quiz looks kind of basic. Hopefully we have time to work on that. In terms of functionality it seems fine though I didn't really understand the second question.

The quizzes.ejs page is not at all what I expected. I assumed that all of the internal pages were going to have the sidebar on the left and the content on the right but it seems like you based that page on the landing page. I think that will need to be scrapped. I was imagining something more like the admin.ejs page to be honest. It's not that big of deal though because that page won't be hard to do.

In terms of routing, what you decided to do should work but you should make sure to check to see that the parameter is valid before displaying the page.

**Comment by brycerandolph** [comment]
I have made several fixes, specifically, question 2 was fixed as it had a typo. I am going to leave the styling of the page to @apainintheneck.

**Comment by brycerandolph** [comment]
I made some changes to add the new sidebar and put the quiz content on a card in the center of the page, but I can't seem to get the quiz links card to center. I also noticed that I don't have the newest sidebar partial because it looks like the older version.

**Comment by apainintheneck** [comment]
I merged in main and added a new /quizzes landing page at quizzes.ejs.

**Comment by apainintheneck** [comment]
I think this can be merged in for now. In the future, I'd like to figure out a way to add the sidebar to each of the quiz pages.

**Pull request merged**
