### PR TITLE
Updated styles on chapter.ejs page to match the rest of the site.

### PR DESCRIPTION
**Pull request by apainintheneck**
You can see the changes by going to the /lecture page and clicking on one of the chapters that has been submitted (mine or Bryce's).

1. Updated styles on chapter.ejs page by modifying that file and the chapter.js file. Styles are based on those used throughout the site.
2. Added mb-5 to a whole bunch of pages so that users can scroll to the bottom and there is a bit of space between the last eleement on the page and the bottom. This is just a small visual change.
3. Removed marked.js import statement from head.js and added it directly to chapter.ejs because that is the only page in the project which needs that library.

In the future, I think it would be nice to target content on the page specifically with CSS and see if we can change the default marked.js options to display content in a more pleasing way. That being said I think this is a huge improvement and is a good step forward.

### CODE REVIEW

**Comment by brycerandolph** [comment]
I like what you have done with these latest changes. Visually much more appealing. I saw one visual issue with the image used in chapter 3. It does not seem to resize properly.
image

**Comment by apainintheneck** [comment]
Yep, that was one of things that I needed to work on. Here are the most recent changes.

1. Responsive Images
Screen Shot 2021-11-28 at 6 55 49 PM

2. Bootstrap Tables
Screen Shot 2021-11-28 at 6 56 04 PM

3. New Nav Buttons
Screen Shot 2021-11-28 at 8 34 26 PM

**Comment by apainintheneck** [comment]
The only other thing that could be added is better styling for code tags or even automatic code highlighting but I'm not sure how much of a priority those are right now.

**Comment by brycerandolph** [comment]
One thing that sticks out to me is the lack of space between the nav buttons. I think having 3 distinct buttons separated by a bit of white space would be more aesthetically pleasing. Here is a quick mockup. 
image

**Comment by apainintheneck** [comment]
A few more style updates. Let me know if there is anything else you'd like me to add.

1. Added spacing between nav buttons.
2. Set default line breaks in marked.js so the overuse of `<br>` is probably over now.
3. Centered all header tags (`H1, H2, H3, ...` in html and `#, ##, ###, ...` in markdown).
4. Added underlines to header tags H1 through H4.

I updated my pages to work with these style changes. The rest of the pages would need to be updated as well. 

You can see the results here: https://sqlstudy.herokuapp.com/chapter?id=3

**Pull request merged**
